### ISSUE TITLE
Walmart Canada Response Errors

### ISSUE THREAD

**Issue by quocvu88** [highsidelabs/walmart-api-php#14]
Hello,
When I use SDK to call getOrders or getItems, it reponse fatal error like this:

`Fatal error: Uncaught TypeError: Walmart\Apis\MP\CA\OrdersApi::getAllOrdersWithHttpInfo(): Return value must be of type Walmart\Models\MP\CA\Orders\WFSOrdersListType, null returned in /var/www/vhosts/svc-walmart/public_html/vendor/highsidelabs/walmart-api/src/Apis/MP/CA/OrdersApi.php:814 Stack trace: #0 /var/www/vhosts/svc-walmart/public_html/vendor/highsidelabs/walmart-api/src/Apis/MP/CA/OrdersApi.php(721): Walmart\Apis\MP\CA\OrdersApi->getAllOrdersWithHttpInfo() #1 /var/www/vhosts/svc-walmart/public_html/orders.php(44): Walmart\Apis\MP\CA\OrdersApi->getAllOrders() #2 {main} thrown in /var/www/vhosts/svc-walmart/public_html/vendor/highsidelabs/walmart-api/src/Apis/MP/CA/OrdersApi.php on line 814`

The sames type of error with getItems
`Fatal error: Uncaught TypeError: Walmart\Apis\MP\CA\ItemsApi::getAllItemsWithHttpInfo(): Return value must be of type Walmart\Models\MP\CA\Items\ItemResponses, null returned in /var/www/vhosts/svc-walmart/public_html/vendor/highsidelabs/walmart-api/src/Apis/MP/CA/ItemsApi.php:490 Stack trace: #0 /var/www/vhosts/svc-walmart/public_html/vendor/highsidelabs/walmart-api/src/Apis/MP/CA/ItemsApi.php(409): Walmart\Apis\MP\CA\ItemsApi->getAllItemsWithHttpInfo() #1 /var/www/vhosts/svc-walmart/public_html/items.php(44): Walmart\Apis\MP\CA\ItemsApi->getAllItems() #2 {main} thrown in /var/www/vhosts/svc-walmart/public_html/vendor/highsidelabs/walmart-api/src/Apis/MP/CA/ItemsApi.php on line 490`

But in debug file, API reponse was successful
`[2023-10-06 15:49:18]: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns3:list xmlns:ns2="http://walmart.com/mp/orders" xmlns:ns3="http://walmart.com/mp/v3/orders" xmlns:ns4="http://walmart.com/"><ns3:meta><ns3:totalCount>3</ns3:totalCount><ns3:limit>10</ns3:limit></ns3:meta><ns3:elements><ns3:order><ns3:purchaseOrderId>Y12345678</ns3:purchaseOrderId><ns3:customerOrderId>4540000000000</ns3:customerOrderId>`

OrderID edited.

Please help me to check this.
Thank you!

**Comment by joeybab3** [comment]
Did you ever end up fixing this?
